baseURL = 'https://koalaquakes.github.io/devops-journey/'
languageCode = 'en-us'
title = 'Shane Hart | DevOps Journey'
theme = "LoveIt"

[menu]

[[menu.main]]
identifier = "posts"
name = "Posts"
url = "/posts/"
weight = 1

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 2

[params.page.toc]
  enable = true
  keepStatic = false
  auto = true

[params]
  defaultTheme = "auto"
  dateFormat = "2006-01-02"

[params.header]
  desktopMode = "fixed"
  mobileMode = "auto"
  [params.header.title]
    name = "DevOps Journey"

[params.footer]
  enable = true
  hugo = true

[params.home.profile]
  enable = true
  avatarURL = "images/profile.jpg"
  title = "Shane Hart"
  subtitle = "Cloud, DevOps & Cyber Security"
  typeit = true

  social = true

[params.page.code]
  copy = true

# Social link icons to share on social platforms under Posts
[params.page.share]
  enable = false

[params.social]
GitHub = "KoalaQuakes"
Linkedin = "hart-shane"

[params.search]
  enable = true
  type = "lunr"

[params.author]
  name = "Shane"

[markup]
  [markup.highlight]
    noClasses = false

[markup.goldmark.renderer]
  unsafe = true
